//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPlanner.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Stories")]
    public partial class Story
    {
        [Key]
        public int StoryId { get; set; }
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public Nullable<int> EpicId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<decimal> StoryPoints { get; set; }
        public Nullable<int> Benefit { get; set; }
        public Nullable<int> Penality { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string CreatedBy { get; set; }
        public string AssigneeName { get; set; }
        public string SprintName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public string Tag { get; set; }
        public string Status { get; set; }
        public string Release { get; set; }
        public string Milestone { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Epic Epic { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
